PATTERN BASIC_READ
PINS CLK CS_N WE_N RE_N RESET_N DQ[7:0]
TIMESET FAST_5NS
VECTOR 0: CLK=0 CS_N=1 WE_N=1 RE_N=1 RESET_N=0 DQ=ZZ
VECTOR 1: CLK=1 CS_N=1 WE_N=1 RE_N=1 RESET_N=1 DQ=ZZ
VECTOR 2: CLK=0 CS_N=0 WE_N=1 RE_N=0 RESET_N=1 DQ=ZZ
VECTOR 3: CLK=1 CS_N=0 WE_N=1 RE_N=0 RESET_N=1 DQ=EXPECT_A5
ENDPATTERN
